import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Link from 'next/link';
import ImgCard from '../comps/ImgCard';
import Navbar from "../comps/Navbar"
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Navbar/>
    <Link href="/boiler">Go to Boiler</Link>
    <ImgCard
    bg="#000000" 
    />
    <ImgCard
    tcl="#abc980"
    img="https://placekitten.com/100/100" />
    </div>
  )
}
